var nameOfPlaceForm = document.getElementById("name-of-place-form")
var nameOfLocationForm = document.getElementById("name-of-location-form")
var whereToGo = new WhereToGo()
var app = new App(whereToGo, nameOfPlaceForm, nameOfLocationForm)
app.start()
